### ISSUE TITLE
A question about the calculation of kernel estimated density p(s)

### ISSUE THREAD

**Issue by gongshuai0606** [mingchenaabb/StKE_train#1]
Hi,For the line 87 `return k.sum(axis=1) * (1./W_t.sum())` of the density_est() of the core.py of dmap, it calculates the Σ[wi*K(s, si)] / Σwi, which seems different from the calculation of the kernel estimated density of p(s) = Σw*K(s, si) in eq 4 in the supplemental of the paper "Unfolding Hidden Barriers by Active Enhanced Sampling"

**Comment by mingchenPurdueChem** [comment]
I think it just to enforce nomalizing the weights in case the weight is not normalized
